### ISSUE TITLE
bug: idTokenClaim user picture null because it's called avatar

### ISSUE THREAD

**Issue by wildsylvan** [logto-io/dart#63]
https://github.com/logto-io/dart/blob/08e2f3cb27d543a01da4a7ee349c99ae2a44fe6b/lib/src/modules/id_token.dart#L16

the json contains a field called `picture`
![image](https://github.com/user-attachments/assets/d5ed366d-6506-4977-be14-7fab62d9965d)

**Comment by simeng-li** [comment]
Thx for the report.
