### ISSUE TITLE
bug: `_getAccessTokenByRefreshToken` saves the access token with scopes, `getAccessToken` reads the access token without scopes

### ISSUE THREAD

**Issue by wildsylvan** [logto-io/dart#65]
and this makes it so `getAccessToken` can never find an access token saved by `_getAccessTokenByRefreshToken` in the `_accessTokenMap` (and so every call to `getAccessToken`, makes a call to the logto endpoint to get an access token)

before using the refresh token for the first time, it works correctly because `_handleSignInCallback` uses `save` which saves the access token without scopes

in the [docs](https://docs.logto.io/docs/references/sdk-convention/platform-sdk-convention/) it is said:
> We set the scope to null when building the key of the accessTokenMap for we don't support custom scopes in Logto V1.

**Comment by simeng-li** [comment]
Thanks looking into it

**Comment by simeng-li** [comment]
@wildsylvan please check the latest release v2.1.0 for the fix.
