### ISSUE TITLE
bug: invalid_grant when refreshing token

### ISSUE THREAD

**Issue by Anotherjez** [logto-io/dart#66]
### Describe the bug

The error occurs when a user's token expires and he tries to fetch the access token with the refresh token to get user data with `.getUserInfo()` function. This error only occurs with previously authenticated users and We are only using discord social connector for sign-in and sign-up. It seems that the error occurs with **discord users who have 2FA**.

This error may be related to [this bug.](https://github.com/logto-io/dart/issues/65)

### Expected behavior

`.getUserInfo()` working without errors.

### How to reproduce?

1. Sign in with discord account (with 2FA)
2. Wait for the token to expire
3. Open the app again and try to get `logtoClient.isAuthenticated`
4. Try to get `logtoClient.getUserInfo()` without errors

### Context

- This error has been happening since June.
- Using the latest version of logto_dart_sdk.

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots
![image](https://github.com/user-attachments/assets/376e788b-7eec-44f9-a71c-e4b4bcbb0d65)

**Comment by simeng-li** [comment]
@Anotherjez is the issue the same as this one https://github.com/logto-io/logto/issues/5970?
This should have been addressed in v2.0.1 already. I believe you have confirmed the fix in the above issue.  Please let me known if you still seeing this.

**Comment by simeng-li** [comment]
The `invalid_grant` error is triggered by the token exchange endpoint (`fetchTokenByRefreshToken`). Based on the logs you provided, it’s likely that your `refresh_token` has expired. You’ll need to handle this error manually by clearing the native storage and redirecting the user to the sign-in page.

By default, the refresh_token has a TTL of 14 days, but you can modify this setting on your App details page.

**Comment by Anotherjez** [comment]
> @Anotherjez what SDK version were you using? Is this the same issue you reported [earlier](https://github.com/logto-io/logto/issues/5970)?

Not the same issue, using logto_dart_sdk 2.0.2.

> #65 shouldn't affect it, as the SDK will always request a new access token using the refresh token if no valid token is found in storage.

But I always get the error when the sdk requests the new access token. 

> Based on the logs you provided, it’s likely that your `refresh_token` has expired.

I don't think so. The refresh token should not expire daily. All my users had to sign in again everyday.

> By default, the refresh_token has a TTL of 14 days, but you can modify this setting on your App details page.

Yes, in my settings it is set to 14 days.

**Comment by simeng-li** [comment]
I have set my accss_token ttl to 1min, so I can test the token exchange flow easily.  Still can't reproduce the issue. Can you share your Logto configs? Wondering what I am missing here.

**Comment by Anotherjez** [comment]
Sorry for taking so long, MongoDB has announced the end of life of Realm Device Sync and for this project I was also using MongoDB for authentication along with Logto. 

Now that I only use Logto for authentication, it seems that the problem is solved.
